version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file:
      - .env
    volumes:
      - ./data/:/app/data/
      - static:/static
      - media:/media
    depends_on:
      - db

  frontend:
    build: ./frontend/
    env_file:
      - .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: nginx:1.22.1
    ports:
      - "9090:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/static/api/docs/
      - static:/static
      - media:/media
